version: "3.8"
services:
  web:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - env/web.env
  worker:
    build: .
    env_file:
      - env/web.env
    entrypoint: ["poetry", "run", "celery", "-A", "webhook_receiver:celery", "worker"]
  redis:
    image: redis